[package]
name = "native-hotkeys"
version = "0.1.0"
authors = ["dhardtke"]
edition = "2018"

[dependencies]
windows = "0.10.0"
configparser = "2.0.1"

[build-dependencies]
windows = "0.10.0"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
